### PR TITLE
Add native installation instructions for beginners

### PR DESCRIPTION
**Pull request by ani-hovhannisyan**
This file contains detailed explanations for newcomer developers to install SW360 source code natively without docker into their Debian based machine.
This guidance has notes and cautions about Liferay dependencies being not properly installed, which might not be found in currently available English Documentations.

Issue: Related to installation documentation

How To Test?
Clone the sw360 repository in a freshly installed Debian (tested on Ubuntu 20.04) machine
Follow the instruction steps written in the README_BEGINNER_INSTALLATION.md, and see whether the last step brings you to the SW360 portal normally working page.

### CODE REVIEW

**Review by heliocastro — CHANGES_REQUESTED** [review]
I think this is misleading. You are requesting changes for README.md on the website instead of the sw360 repository

Should this be made as a page to be show on sw360 website ?
So this page should be added here: https://github.com/eclipse/sw360.website/tree/main/content/en/docs/

And maybe on main sw360 repo as well.

But for sure README.md is not the correct place for this info

**Comment by ani-hovhannisyan** [comment]
Thank you very much for prompt response. 
> I think this is misleading. You are requesting changes for README.md on the website instead of the sw360 repository

I'm sorry.
> Should this be made as a page to be show on sw360 website ? So this page should be added here: 

https://github.com/eclipse/sw360.website/tree/main/content/en/docs/
 
> And maybe on main sw360 repo as well.

At the moment, there is an issue with ECA agreement for committer, once I fix it will be able to PR in sw360 as well.

> But for sure README.md is not the correct place for this info

Sure, will move to the https://github.com/eclipse/sw360.website/tree/main/content/en/docs/Deployment/Legacy with the name "Native Installation for beginner.md", as there is another Native installation guidance.

**Comment by heliocastro** [comment]
Maybe you can replace the original native. There's no reason to have both
:-)

**Comment by ani-hovhannisyan** [comment]
> Maybe you can replace the original native. There's no reason to have both :-)

Ok, I did version 16 installation changes on top of version 14 installation instructions, as it has different flow of instructions, might be useful too.

**Review by heliocastro — COMMENTED** [review]
LGTM

**Comment by heliocastro** [comment]
Thanks for the first submission

**Pull request merged**
