### PR TITLE
Bug 551892 - [CJE2JIRO] Migration of SW360 JIPP to Jiro

### PR DESCRIPTION
**Pull request by fredg02**
Fix credentials ID and set HOME environment variable

Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>

### CODE REVIEW

**Comment by fredg02** [comment]
Ping.

**Comment by bs-jokri** [comment]
@fredg02 Sorry, completely overlooked your PR.

**Comment by fredg02** [comment]
No worries.

**Comment by bs-jokri** [comment]
@fredg02 BTW.: the website build is running and green again. Thanks for that!

**Pull request merged**
